@isTest
private  class AccountTriggerHandlerTest {
    /** Test methods needs to be designed for class AccountTriggerHandler to meet code coverage requirements.
     * Design methods in the beforeInsert and after insert test method
     */
    
    @isTest 
    static void testbeforeInsert() {
        // Read and understand the funtionality in the method handleBeforeInsert in AccountTrigger Handler
        // Test method should try to create and insert an Account programatically and 
        // Assert that the correct priority has been set by creating account with different Estimated Annual Sales
    
    
    }

    @isTest 
    static void testafterInsert() {
         // Read and understand the funtionality in the method handleAfterInsert in AccountTrigger Handler
        // Test method should try to create and insert an Account programatically and 
        // Assert that case has been created for the Accounts inserted and field values are set correct in Case
        
    
    
    }

    //Bonus: Look at the additional method in AccountTriggerHandler and add test methods. 
   
}