public class RadException extends Exception {
//This is a very basic custom exception class which extends the standard Salesforce Exceptions
//It allows us to throw exceptions based on our own rules.  There is much more that we can do with a custom exception
//(Send an email notification, save a record of the exception etc.)
//For more information: https://developer.salesforce.com/docs/atlas.en-us.apexcode.meta/apexcode/apex_exception_custom.htm?search_text=custom%20exception



}