/**
 * A Utility class to process Stock Item records from the Stock Item Handler
 */
public with sharing class StockItemHandler {
    
    /**
     * Class constructor.
     */
    public StockItemHandler() {
        
    }

    //Create methods here to handle the before insert, before delete and utility processes described in the requirements
    //They should accept lists of Stock_Item__c records from the trigger

    
}