public with sharing class WeekOneClassExercises {
    
	public static void talkingAboutPrimitives() {
        //Lets declare some primitives!
        Integer i;

        //What are some other types we can declare?
        String s;
        Decimal d;

        //Assigning Values
        i = 2;
        s = 'Mr. Stringy';

        //More commonly you can declare a variable and assign it a value in the same operation
        Integer j = 3;
        String str = 'Ms. String';
        Decimal dec = 3.14;

        //Using some of those values
        Integer result = i + j;  //Since we assigned i a value of 2 and j a value of 3, result is now equal to 5

    }
}
