public with sharing class WeekFiveHomework {
    
	 //Assignment:  The following method is supposed to create the number of accounts specified in the argument that it takes.
    //Each Account should be named 'Sample Account #sampleNumber'  where sample number is the count.  So if you created 2 Accounts
    //one would be called 'Sample Account 1' and the other 'Sample Account 2'

    //Also, when we're done inserting them, we will create a case for each one with a Status of 'New', Origin of 'New Account' and the
    //desription and subject of your choice.

    //This isn't working quite right.  Can you use your debugging skills to fix it?  I had to comment it out since it won't compile
    //Look out for consistency and formatting too!  (even if they don't break the code)
    //Add comments to describe what the code is doing.
    //After you get it to compile, run it in execute anonymous and check that it's really working!  Look up your new accounts in your org!

    public static void createSampleAccounts(Decimal numberOfAccounts) {

        /*      List<Account> acctList = new List<Account>();
                for (Integer i = 0; i <= numberOfAccounts; i++) {
                    Account a = new Account();
                    a.Name = 'NewAccount';
                }
        
                insert acctList;
        
                List<Case> casesToInsert = new List<Case>();
        
                for (Account a: accctList) {
                    Case c = new Case();
                    c.Status = "New";
                    c.Origin = 'New Account'
                    c.AccountId = a;
                    c.Subject 'New Case';
                    c.Descritpion == 'Follow Up';
                    casesToInsert.add(c);
        
                }*/
        
            }



}